// Mocks generated by Mockito 5.4.4 from annotations
// in tracker_frontend/test/services/directions_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_maps_flutter/google_maps_flutter.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tracker_frontend/data/client/google_routes_api_client.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRouteResult_0 extends _i1.SmartFake implements _i2.RouteResult {
  _FakeRouteResult_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [GoogleRoutesApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleRoutesApiClient extends _i1.Mock
    implements _i2.GoogleRoutesApiClient {
  MockGoogleRoutesApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RouteResult> getWalkingRoute(List<_i4.LatLng>? waypoints) =>
      (super.noSuchMethod(
        Invocation.method(#getWalkingRoute, [waypoints]),
        returnValue: _i3.Future<_i2.RouteResult>.value(
          _FakeRouteResult_0(
            this,
            Invocation.method(#getWalkingRoute, [waypoints]),
          ),
        ),
      ) as _i3.Future<_i2.RouteResult>);

  @override
  _i3.Future<_i2.RouteResult> getDrivingRoute(List<_i4.LatLng>? waypoints) =>
      (super.noSuchMethod(
        Invocation.method(#getDrivingRoute, [waypoints]),
        returnValue: _i3.Future<_i2.RouteResult>.value(
          _FakeRouteResult_0(
            this,
            Invocation.method(#getDrivingRoute, [waypoints]),
          ),
        ),
      ) as _i3.Future<_i2.RouteResult>);
}

