// Mocks generated by Mockito 5.4.6 from annotations
// in tracker_frontend/test/services/user_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tracker_frontend/data/client/command/user_command_client.dart'
    as _i5;
import 'package:tracker_frontend/data/client/query/user_query_client.dart'
    as _i3;
import 'package:tracker_frontend/data/models/user_models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProfile_0 extends _i1.SmartFake implements _i2.UserProfile {
  _FakeUserProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserQueryClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserQueryClient extends _i1.Mock implements _i3.UserQueryClient {
  MockUserQueryClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserProfile> getUserById(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<_i2.UserProfile> getUserByUsername(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByUsername,
          [username],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getUserByUsername,
            [username],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<_i2.UserProfile> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<List<_i2.Friendship>> getFriends() => (super.noSuchMethod(
        Invocation.method(
          #getFriends,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Friendship>>.value(<_i2.Friendship>[]),
      ) as _i4.Future<List<_i2.Friendship>>);

  @override
  _i4.Future<List<_i2.FriendRequest>> getReceivedFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReceivedFriendRequests,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.FriendRequest>>.value(<_i2.FriendRequest>[]),
      ) as _i4.Future<List<_i2.FriendRequest>>);

  @override
  _i4.Future<List<_i2.FriendRequest>> getSentFriendRequests() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSentFriendRequests,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.FriendRequest>>.value(<_i2.FriendRequest>[]),
      ) as _i4.Future<List<_i2.FriendRequest>>);

  @override
  _i4.Future<List<_i2.UserFollow>> getFollowing() => (super.noSuchMethod(
        Invocation.method(
          #getFollowing,
          [],
        ),
        returnValue: _i4.Future<List<_i2.UserFollow>>.value(<_i2.UserFollow>[]),
      ) as _i4.Future<List<_i2.UserFollow>>);

  @override
  _i4.Future<List<_i2.UserFollow>> getFollowers() => (super.noSuchMethod(
        Invocation.method(
          #getFollowers,
          [],
        ),
        returnValue: _i4.Future<List<_i2.UserFollow>>.value(<_i2.UserFollow>[]),
      ) as _i4.Future<List<_i2.UserFollow>>);
}

/// A class which mocks [UserCommandClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCommandClient extends _i1.Mock implements _i5.UserCommandClient {
  MockUserCommandClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserProfile> createUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [userData],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #createUser,
            [userData],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);

  @override
  _i4.Future<String> sendFriendRequest(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [userId],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #sendFriendRequest,
            [userId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> acceptFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #acceptFriendRequest,
            [requestId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> deleteFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFriendRequest,
          [requestId],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #deleteFriendRequest,
            [requestId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> removeFriend(String? friendId) => (super.noSuchMethod(
        Invocation.method(
          #removeFriend,
          [friendId],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #removeFriend,
            [friendId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> followUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [userId],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #followUser,
            [userId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> unfollowUser(String? followedId) => (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [followedId],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #unfollowUser,
            [followedId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.UserProfile> updateProfile(
          _i2.UpdateProfileRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [request],
        ),
        returnValue: _i4.Future<_i2.UserProfile>.value(_FakeUserProfile_0(
          this,
          Invocation.method(
            #updateProfile,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.UserProfile>);
}
